In [8]:
import pandas as pd
import numpy as np

In [9]:
sample_data = {
    "NDVI": [0.75, 0.42, 0.15, 0.67, 0.42],
    "NDBI": [0.20, 0.55, 0.80, 0.30, 0.65],
    "LST": [28.5, 35.2, 41.8, 30.4, 38.7],
    "PopulationDensity": [1200, 4500, 8000, 2000, 6000],
    "Humidity": [65, 55, 40, 70, 50],
    "WindSpeed": [12, 8, 5, 15, 7]
}

df = pd.DataFrame(sample_data)

df

   NDVI  NDBI   LST  PopulationDensity  Humidity  WindSpeed
0  0.75  0.20  28.5               1200        65         12
1  0.42  0.55  35.2               4500        55          8
2  0.15  0.80  41.8               8000        40          5
3  0.67  0.30  30.4               2000        70         15
4  0.42  0.65  38.7               6000        50          7

In [10]:
df["Green_Built_Ratio"] = (
    df["NDVI"] /
    (df["NDBI"] + 0.01)
)

df

   NDVI  NDBI   LST  PopulationDensity  Humidity  WindSpeed  Green_Built_Ratio
0  0.75  0.20  28.5               1200        65         12           3.571429
1  0.42  0.55  35.2               4500        55          8           0.750000
2  0.15  0.80  41.8               8000        40          5           0.185185
3  0.67  0.30  30.4               2000        70         15           2.161290
4  0.42  0.65  38.7               6000        50          7           0.636364

In [11]:
df["Cooling_Potential"] = (
    df["NDVI"] *
    df["Humidity"]
)

df

,NDVI,NDBI,LST,PopulationDensity,Humidity,WindSpeed,Green_Built_Ratio,Cooling_Potential
0,0.75,0.20,28.5,1200,65,12,3.571429,48.75
1,0.42,0.55,35.2,4500,55,8,0.750000,23.10
2,0.15,0.80,41.8,8000,40,5,0.185185,6.00
3,0.67,0.30,30.4,2000,70,15,2.161290,46.90
4,0.42,0.65,38.7,6000,50,7,0.636364,21.00

In [12]:
df["Heat_Exposure_Index"] = (
    df["NDBI"] *
    df["PopulationDensity"]
)

df

,NDVI,NDBI,LST,PopulationDensity,Humidity,WindSpeed,Green_Built_Ratio,Cooling_Potential,Heat_Exposure_Index
0,0.75,0.20,28.5,1200,65,12,3.571429,48.75,240.0
1,0.42,0.55,35.2,4500,55,8,0.750000,23.10,2475.0
2,0.15,0.80,41.8,8000,40,5,0.185185,6.00,6400.0
3,0.67,0.30,30.4,2000,70,15,2.161290,46.90,600.0
4,0.42,0.65,38.7,6000,50,7,0.636364,21.00,3900.0

In [13]:
df.columns

Index(['NDVI', 'NDBI', 'LST', 'PopulationDensity', 'Humidity', 'WindSpeed',
       'Green_Built_Ratio', 'Cooling_Potential', 'Heat_Exposure_Index'],
      dtype='str')

In [14]:
X = df.drop("LST", axis=1)

y = df["LST"]

print("Features:")
print(X.columns)

print("\nTarget:")
print(y.name)

Features:
Index(['NDVI', 'NDBI', 'PopulationDensity', 'Humidity', 'WindSpeed',
       'Green_Built_Ratio', 'Cooling_Potential', 'Heat_Exposure_Index'],
      dtype='str')

Target:
LST